[project]
name = "ai-agent-from-scratch"
version = "0.1.0"
description = "A Python terminal-based AI coding agent supporting Groq and Google Gemini. It uses tool calling to search, read, modify, and manage files, execute shell commands, and assist with coding tasks through human-confirmed actions."
readme = "README.md"
authors = [
    { name = "Shivansh", email = "" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.22.0",
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-agent-from-scratch = "ai_agent_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
